sudo: required

os:
  - linux

language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

addons:
  chrome: stable

install:
  - composer self-update
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - phpenv rehash

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit --coverage-clover clover.xml
  - php artisan dusk

after_script:
  - php vendor/bin/codacycoverage clover clover.xml
